### ISSUE TITLE
support for SM6150

### ISSUE THREAD

**Issue by nookgit12** [edk2-porting/edk2-msm#411]
plz i dont know how to write these config files so i want to ask yall to make config for SM6150 (snapdragon 675)

**Comment by sndnvaps** [comment]
@nookgit12 i have init the project for xiaomi note 7 pro(violet), platform is sm6150
now it can build boot-violet.img, but need more time to dump the dsdt.aml from my cell phone

**Comment by sndnvaps** [comment]
when i try to port edk2 to sm6150 platform, i had got some trouble
like this

![Image](https://github.com/user-attachments/assets/45699c97-3cd7-4e40-9814-80107e7fe601)

is any one can give me some advices....

**Comment by Sasmithere** [comment]
can you send the boot-violet.img ? i used dipper img(personal modified version) to use split emmc partitions to win esp etc ...
so far i am not able to make a boot img for it

**Comment by sndnvaps** [comment]
@Sasmithere in xiaomi_violet-edk2-boot-violet.zip contains 2 file, edk2-boot-violet.img and edk2-boot-violet-old.img

[xiaomi_violet-edk2-boot-violet.zip](https://github.com/user-attachments/files/22451810/xiaomi_violet-edk2-boot-violet.zip)

**Comment by Sasmithere** [comment]
i'll try both and return with an update

**Comment by Sasmithere** [comment]
@sndnvaps the old img one seems to boot into efi shell but my otg usb keyboard doesn't seem to work , i was wondering if you still have the .dsc , .fdf and .conf related files for it , i want to change the cmdline so it automatically boots to windows partition

**Comment by Thirumal-Palwai** [comment]
Hey @sndnvaps @Sasmithere 

I came across this project and thought it might be useful for your work:

GitHub: https://github.com/Project-Aloha/mu_aloha_platforms
Porting Guide: https://aloha.firmware.icu/PortingGuides/SimpleGuide.html

**Comment by Sasmithere** [comment]
@sndnvaps thanks for the files ,
 The graphicsconsoledxe.efi is causing the ruckus I'll be approaching this issue in these ways :
1. fix the graphicsconsoledxe.efi by dumping and recompiling then insert some dummy registers which are causing the issue and i did saw some registers having <unknown> as address (hard)
2. use a dummy graphicsconsoledxe.efi which returns efi_success as true and goes to text based interface (medium)
3. change the stack in which graphicsconsoledxe is called and remove it from there , inshort remove it from the call stack(hard) 
4. build graphicsconsoledxe from scratch myself from the xbl.elf file or search internet for something similar (very hard 💀)
5. and last is i will try to change the bootdef.c and boot.c so it automatically boots into uefi boot menu

**Comment by Sasmithere** [comment]
@sndnvaps 

<img width="774" height="442" alt="Image" src="https://github.com/user-attachments/assets/00d0ee23-ff10-423d-90b8-32631a1e86d5" />

is emmc storage not supported ?

**Comment by Sasmithere** [comment]
close 🤏🏻  but no touchscreen and pwm , vol_up and down work  , just scripted to auto boot to simple-init 

![Image](https://github.com/user-attachments/assets/77e48a47-87d7-4713-91f0-175289a618c6)

**Comment by sndnvaps** [comment]
@Sasmithere i cherry-pick you changed, but still get dark screen. you need to push patched file to https://github.com/Sasmithere/edk2-msm-binary/tree/main/Drivers/sm6150  , so i can make a fully test

**Comment by Sasmithere** [comment]
@sndnvaps  i'll upload here my current working set

[edk2-violet.zip](https://github.com/user-attachments/files/23201000/edk2-violet.zip)

**Comment by sndnvaps** [comment]
@Sasmithere in this commit https://github.com/BigfootACA/simple-init/blob/29e062805776db5ab7a61d07ef040d43aed71161/libs/lvgl/README.md, Features, support touch screen, 
it make do some hack to make it work....

**Comment by Sasmithere** [comment]
@sndnvaps TouchScreen config is in DisplayDxe.efi , but when i include it , it restarts the device

**Comment by Sasmithere** [comment]
i made WLED, IBB, LAB, LCDB to return EFI_SUCCESS and it work, but no touch still but before booting to tianocore  ,debug error : 

```
MDPSystem: Failed to set variable <DisplaySupportedPanelCount>. Error: 00000002
MDPSystem: Failed to set variable <DisplaySupportedPanelList>. Error: 00000002

```
0x2 likely meaning not found

[StubPmicDxe.c](https://github.com/user-attachments/files/23268700/StubPmicDxe.c)

corresponding inf :
 ```
[Defines]
  INF_VERSION    = 0x00010005
  BASE_NAME      = StubPmicDxe
  FILE_GUID      = 12345678-1234-1234-1234-123456789ABC
  MODULE_TYPE    = DXE_DRIVER
  VERSION_STRING = 1.0
  ENTRY_POINT    = StubPmicEntry

[Sources]
  StubPmicDxe.c

[Packages]
  MdePkg/MdePkg.dec

[LibraryClasses]
  UefiDriverEntryPoint
  UefiBootServicesTableLib

[Depex]
  TRUE
```

**Comment by J0SH1X** [comment]
Touch in uefi needs a driver aka touchscreendxe but there is only one for synaptics Touchscreens and also iirc to make touch work you need to recompile i2cdxe and gpidxe (at least on sm8150)

**Comment by sndnvaps** [comment]
@J0SH1X you mean do some hack to I2C.efi & GpiDxe.efi to make the TouchScreen work.

**Comment by Sasmithere** [comment]
@sndnvaps i patched the .efi and added Panel_shenchao_nt36672a_fhd_video.xml from raw files no reboots now and ,i follwed sm8150 pattern DisplayDxe.efi @J0SH1X , but still no touch .... need to hack i2cdxe and gpidxe ?, what to change in i2cdxe and gpidxe exactly ?i have no idea on that one

[DisplayDxe.zip](https://github.com/user-attachments/files/23286456/DisplayDxe.zip)

**Comment by sndnvaps** [comment]
@Sasmithere i have not idea too. 
@J0SH1X i want to compile the I2cdxe from source, but cannt build in src tree.  can give us some idea, how to hack the i2cdxe & gpidxe

**Comment by Sasmithere** [comment]
@sndnvaps 
my current implementation shows that usb is detected in tianocore , will that help ? i have attached below
debug
```
UsbConfigPortsQueryConnectionChange: Detach and Type-C

UsbConfigPortsQueryConnectionChange: usbport->connectstate: DEATT

ConfigPortsQueryConnectionChange: UFP and Type-C 

UsbConfigPortsQueryConnectionChange: usbport->connectstate: ATT
```
[Apriori.Dxe.zip](https://github.com/user-attachments/files/23338039/Apriori.Dxe.zip)

**Comment by sndnvaps** [comment]
> [@sndnvaps](https://github.com/sndnvaps) my current implementation shows that usb is detected in tianocore , will that help ? i have attached below debug
> 
> ```
> UsbConfigPortsQueryConnectionChange: Detach and Type-C
> 
> UsbConfigPortsQueryConnectionChange: usbport->connectstate: DEATT
> 
> ConfigPortsQueryConnectionChange: UFP and Type-C 
> 
> UsbConfigPortsQueryConnectionChange: usbport->connectstate: ATT
> ```
> 
> [Apriori.Dxe.zip](https://github.com/user-attachments/files/23338039/Apriori.Dxe.zip)
> 
> i got this debug below in loggerd viewer
> 
> ```
> lvgl: [Error] (180.479, +180479) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.479, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.479, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.479, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.479, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.479, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error](180.480, +1) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.480, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.480, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.480, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> lvgl: [Error] (180.480, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212)
> ```

@Sasmithere i had got the same log of lvgl

```
lvgl: [Error] (180.480, +0) _lv_inv_area: detected modifying dirty areas in render (in iv refr.c line #212 
```
and what you changed to make the usb work

i have buy a usb-a-type-c ttl cable, i hope the usb uart can work

**Comment by sndnvaps** [comment]
@Sasmithere i will do the test this night. 
i will change the  
```
gQcomTokenSpaceGuid.PcdDebugUartPortBase|0xa88000
```
to 
```
 gQcomTokenSpaceGuid.PcdDebugUartPortBase|0x880000
```
uart port defind in boot.img file, cmd_line
```
erlycon=msm_geni_serial,0x880000 
```

**Comment by sndnvaps** [comment]
@Sasmithere it seem not thing changed....
touch_screen still not work. 

but int loggerd viewer(we still got the same log)
```
guidrv: try init input driver uefi-touch
uefitouch: found new uefi absolute 0xc9b551f0
uefitouch: receive touch device hot-plug event
```
it may be fix the touch_screen will be easy then fix sdccDxe

**Comment by Sasmithere** [comment]
@sndnvaps 
below is my implementation and i used novatek source code from the violet kernel and 
[violet kernel](https://github.com/Joker-V2/kernel_xiaomi_violet/blob/21c2a2b11b43f3e58384fa6c2338738beab98c73/drivers/input/touchscreen/nvt_touch_f7b/nt36xxx.c)
and 
main ->  [novatek-nvt-ts.c](https://github.com/torvalds/linux/blob/2061f18ad76ecaddf8ed17df81b8611ea88dbddd/drivers/input/touchscreen/novatek-nvt-ts.c)
to code this up 

[NovatekTouchDxe.zip](https://github.com/user-attachments/files/23965083/NovatekTouchDxe.zip)

 and to find the correct i2c i changed the code to

```
  if (I2C_ERROR(I2CStatus)) {
    DEBUG((EFI_D_ERROR,
           "NovatekNvtTsDxe: Failed to open I2C%d: %d. Scanning other IDs...\n",
           Instance->NvtDevice->ControllerI2cDevice, I2CStatus));

    // Debug: Scan for valid I2C IDs
    for (UINT32 i = 0; i < 12; i++) {
      VOID *TempHandle = NULL;
      I2C_STATUS TempStatus = NvtDeviceIo->I2cQupProtocol->Open(i, &TempHandle);
      DEBUG((EFI_D_ERROR, "NovatekNvtTsDxe: Testing I2C ID %d: Status %d\n", i,
             TempStatus));
      if (TempStatus == I2C_SUCCESS) {
        NvtDeviceIo->I2cQupProtocol->Close(TempHandle);
      }
    }

    Status = EFI_DEVICE_ERROR;
    goto exit;
  }
```

through which i found the correct i2c being 4, your i2c may be different 
so now we can update it to 

```
  gQcomTokenSpaceGuid.PcdTouchCtlrAddress|0x62
  gQcomTokenSpaceGuid.PcdTouchCtlrI2cDevice|4
  gQcomTokenSpaceGuid.PcdTouchCtlrResetPin|88
  gQcomTokenSpaceGuid.PcdTouchCtlrIntPin|89
  gQcomTokenSpaceGuid.PcdTouchMaxX|1079
  gQcomTokenSpaceGuid.PcdTouchMaxY|2339
  gQcomTokenSpaceGuid.PcdTouchCtlrVddPin|0
  gQcomTokenSpaceGuid.PcdTouchCtlrVddIoPin|0
```
some more probing is required for touch for now

**Comment by sndnvaps** [comment]
@Sasmithere i will test you code today.
and respond the i2c_bus & i2c_addr

**Comment by sndnvaps** [comment]
@Sasmithere use your driver. the gui res: 1080x2160, 
but not got the i2c error, it seem works. but TouchScreen still OffLine.

at the last, i got the execption occurred

![Image](https://github.com/user-attachments/assets/bf6abdc0-561c-4fca-9df6-b8c79fb12d65)

**Comment by Sasmithere** [comment]
@sndnvaps i found something critical , i2c bus 4 is for display panel but not for touch controller , the touch controller should be on i2c bus 1 at 0x62 but uefi does not open for touch controller , it only opens for display panel through which we see the boot up

**Comment by J0SH1X** [comment]
I told you you need to patch and recompile dalsys and gpi cause of that
exact iusse

Sasmithere ***@***.***> schrieb am So., 7. Dez. 2025, 12:37:

**Comment by Sasmithere** [comment]
@J0SH1X what exactly i need to patch init ? i have played with ghidra long enough .

**Comment by Sasmithere** [comment]
@sndnvaps 
[patches.zip](https://github.com/user-attachments/files/24336145/patches.zip)
1. DALSYSDxe patched to enable i2c 1
2. PILDxe patched to stop any fails due to "Auto processing of uefipil.cfg failed. Calling target panic"
3. DisplayDxe patched from Lavender (redmi note 7) to fallback to shenchao xml instead of VirtioDSI fallback

@J0SH1X  can you tell me more about how can i enable or wake up the touch controller? manual gpio waking config crashes the device

**Comment by Sasmithere** [comment]
@sndnvaps  les go , touch is working , i used software bit magic and i replicated how android did , no need for i2c bus here and some ai stuff(AB testing), for now its sluggish and has ghost touches , i'll fix them, in some time later

[touch.zip](https://github.com/user-attachments/files/24374727/touch.zip)

**Comment by sndnvaps** [comment]
@Sasmithere i will test it tomorrow.

**Comment by sndnvaps** [comment]
@Sasmithere You need to upload the NovatekNvtTsDxe.depex & NovatekNvtTsDeviceDxe.depex for the test . only with *dxe.efi cann't work. we need the depex file to deal with the depend link.

**Comment by Sasmithere** [comment]
@sndnvaps 
add it to dxe.fdf.inc wherever you place 
[NovatekTouchDxe.zip](https://github.com/user-attachments/files/24402774/NovatekTouchDxe.zip)

ghost touch is persistent and touching the display is not being registered , i might need extra hands on that one

**Comment by sndnvaps** [comment]
@Sasmithere with you change. i build the boot-violet.img, but touching still not work.

**Comment by Sasmithere** [comment]
@sndnvaps use all original binaries here, and for PILDxe just include uefipil.cfg in fv main compact must be the same guid extracted from UEFIReader, use below displaydxe , better version of previous one

[NovatekTouchDxe.zip](https://github.com/user-attachments/files/24409574/NovatekTouchDxe.zip) updated 

[DisplayDxe.zip](https://github.com/user-attachments/files/24409540/DisplayDxe.zip)

<img width="1280" height="1012" alt="boot log" src="https://github.com/user-attachments/assets/b765f5fa-9334-4a6f-a9bc-c8a226f6f2c8" />

https://github.com/user-attachments/assets/0cfd65f8-58a0-4ff6-9cc9-1d26e9304662

**Comment by Sasmithere** [comment]
@sndnvaps i have an aftersales screen here, if you have original then it may work better

**Comment by Sasmithere** [comment]
> [@sndnvaps](https://github.com/sndnvaps) use all original binaries here, and for PILDxe just include uefipil.cfg in fv main compact must be the same guid extracted from UEFIReader, use below displaydxe , better version of previous one
> 
> [NovatekTouchDxe.zip](https://github.com/user-attachments/files/24409574/NovatekTouchDxe.zip) updated
> 
> [DisplayDxe.zip](https://github.com/user-attachments/files/24409540/DisplayDxe.zip)
> 
> <img alt="boot log" width="1280" height="1012" src="https://private-user-images.githubusercontent.com/54745598/531510752-b765f5fa-9334-4a6f-a9bc-c8a226f6f2c8.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjczNzA4MTYsIm5iZiI6MTc2NzM3MDUxNiwicGF0aCI6Ii81NDc0NTU5OC81MzE1MTA3NTItYjc2NWY1ZmEtOTMzNC00YTZmLWE5YmMtYzhhMjI2ZjZmMmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTAyVDE2MTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZmQzNTI4OGViNmYyY2FjY2JlMTdmNWY4MzNhZTY5Mzc0ZTY1NzFiMGY5ZDg5MGQ5MDY5Njg0MzdiNjg2MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t9ZTsYq9-j-DLtGswM2YWtQIiKfAYJeeLhWVQoRH3_I">
>  video.mp4

make sure [AUTO] in uefipil.cfg is empty

**Comment by sndnvaps** [comment]
@Sasmithere 
ok, you can upload you build. so i can test it soon. 
it may be  you change a lot to compact the origin edk2 project.

**Comment by Sasmithere** [comment]
@sndnvaps try this 

[boot-violet.zip](https://github.com/user-attachments/files/24433826/boot-violet.zip)

**Comment by sndnvaps** [comment]
@Sasmithere i have test it . touch screen not work for me.

**Comment by Sasmithere** [comment]
@sndnvaps send your adb dump for NVT-ts or focal tech or himax idk, maybe your panel is different, the touch is not perfect , try tapping multiple times , from my standpoint it should work 

![Image](https://github.com/user-attachments/assets/6cf07cd6-1acd-43c3-bf80-7869b7736f68)

**Comment by sndnvaps** [comment]
@Sasmithere 
i use adb shell dumpsys >> dumpsys.txt  to get all the sys info, then use notepad++ to search 

```
  Device 3: NVTCapacitiveTouchScreen
    EventHub Devices: [ 6 ] 
    Generation: 109
    IsExternal: false
    AssociatedDisplayPort: <none>
    AssociatedDisplayUniqueId: <none>
    HasMic:     false
    Sources: KEYBOARD | TOUCHSCREEN
    KeyboardType: 1
    ControllerNum: 0
    Motion Ranges:
      X: source=TOUCHSCREEN, min=0.000, max=1079.000, flat=0.000, fuzz=0.000, resolution=0.000
      Y: source=TOUCHSCREEN, min=0.000, max=2339.000, flat=0.000, fuzz=0.000, resolution=0.000
      PRESSURE: source=TOUCHSCREEN, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
      SIZE: source=TOUCHSCREEN, min=0.000, max=1.000, flat=0.000, fuzz=0.000, resolution=0.000
      TOUCH_MAJOR: source=TOUCHSCREEN, min=0.000, max=2577.208, flat=0.000, fuzz=0.000, resolution=0.000
      TOUCH_MINOR: source=TOUCHSCREEN, min=0.000, max=2577.208, flat=0.000, fuzz=0.000, resolution=0.000
      TOOL_MAJOR: source=TOUCHSCREEN, min=0.000, max=2577.208, flat=0.000, fuzz=0.000, resolution=0.000
      TOOL_MINOR: source=TOUCHSCREEN, min=0.000, max=2577.208, flat=0.000, fuzz=0.000, resolution=0.000
    Keyboard Input Mapper:
      Parameters:
        OrientationAware: true
        HandlesKeyRepeat: false
      KeyboardType: 1
      Orientation: 0
      KeyDowns: 0 keys currently down
      MetaState: 0x0
      DownTime: 0
    Touch Input Mapper (mode - DIRECT):
      Parameters:
        GestureMode: MULTI_TOUCH
        DeviceType: TOUCH_SCREEN
        AssociatedDisplay: hasAssociatedDisplay=true, isExternal=false, displayId=''
        OrientationAware: true
        Orientation: ORIENTATION_0
      Raw Touch Axes:
        X: min=0, max=1079, flat=0, fuzz=0, resolution=0
        Y: min=0, max=2339, flat=0, fuzz=0, resolution=0
        Pressure: min=0, max=1000, flat=0, fuzz=0, resolution=0
        TouchMajor: min=0, max=255, flat=0, fuzz=0, resolution=0
        TouchMinor: unknown range
        ToolMajor: unknown range
        ToolMinor: unknown range
        Orientation: unknown range
        Distance: unknown range
        TiltX: unknown range
        TiltY: unknown range
        TrackingId: min=0, max=65535, flat=0, fuzz=0, resolution=0
        Slot: min=0, max=9, flat=0, fuzz=0, resolution=0
      Calibration:
        touch.size.calibration: GEOMETRIC
        touch.pressure.calibration: physical
        touch.orientation.calibration: none
        touch.distance.calibration: none
        touch.coverage.calibration: none
      Affine Transformation:
        X scale: 1.000
        X ymix: 0.000
        X offset: 0.000
        Y xmix: 0.000
        Y scale: 1.000
        Y offset: 0.000
      Viewport INTERNAL: displayId=0, uniqueId=local:4630946803141208193, port=129, orientation=0, logicalFrame=[0, 0, 1080, 2340], physicalFrame=[0, 0, 1080, 2340], deviceSize=[1080, 2340], isActive=[1]
      DisplayWidth: 1080px
      DisplayHeight: 2340px
      PhysicalWidth: 1080px
      PhysicalHeight: 2340px
      PhysicalLeft: 0
      PhysicalTop: 0
      InputDeviceOrientation: 0
      Translation and Scaling Factors:
        XScale: 1.000
        YScale: 1.000
        XPrecision: 1.000
        YPrecision: 1.000
        GeometricScale: 1.000
        PressureScale: 0.001
        SizeScale: 0.004
        OrientationScale: 0.000
        DistanceScale: 0.000
        HaveTilt: false
        TiltXCenter: 0.000
        TiltXScale: 0.000
        TiltYCenter: 0.000
        TiltYScale: 0.000
      Last Raw Button State: 0x00000000
      Last Raw Touch: pointerCount=0
      Last Cooked Button State: 0x00000000
      Last Cooked Touch: pointerCount=0
      Stylus Fusion:
        ExternalStylusConnected: false
        External Stylus ID: -1
        External Stylus Data Timeout: 9223372036854775807
      External Stylus State:
        When: 9223372036854775807
        Pressure: 0.000000
        Button State: 0x00000000
        Tool Type: 0

'''

**Comment by Sasmithere** [comment]
dmesg , if your phone is rooted, would help alot,
 if rooted use this command 
``` adb shell su -c "dmesg | grep NVT-ts"```  , 
but seeing NVTCapacitiveTouchScreen , touch should work, i deliberately left EFI_D_ERROR , you can see the full debug on display , send that 

> when i try to port edk2 to sm6150 platform, i had got some trouble like this
> 
> ![Image](https://github.com/user-attachments/assets/45699c97-3cd7-4e40-9814-80107e7fe601)
> 
> is any one can give me some advices....

**Comment by sndnvaps** [comment]
i got this from the Recovery( which enable touch screen)
···
violet:/ # dmesg | grep "NVT-ts"
dmesg | grep "NVT-ts"
[    0.794297] [NVT-ts] nvt_driver_init 2321: start
[    0.794330] [NVT-ts] nvt_driver_init 2328: LCM is right! [Vendor]shenchao [IC] nt36672a
[    0.808765] [NVT-ts] nvt_ts_probe 1546: start
[    0.808807] [NVT-ts] nvt_parse_dt 785: novatek,irq-gpio=89
[    0.893837] [NVT-ts] nvt_ts_check_chip_ver_trim 1184: buf[1]=0x0A, buf[2]=0x00, buf[3]=0x00, buf[4]=0x72, buf[5]=0x66, buf[6]=0x03
[    0.893898] [NVT-ts] nvt_ts_check_chip_ver_trim 1210: This is NVT touch IC
[    0.948077] [NVT-ts] nvt_read_pid 431: PID=5916
[    0.948404] [NVT-ts] nvt_ts_probe 1704: int_trigger_type=1
[    0.948514] [NVT-ts] nvt_ts_probe 1716: request irq 182 succeed
[    0.948970] [NVT-ts] nvt_get_oem_data 608: ++
[    0.993557] [NVT-ts] Init_BootLoader 346: Init OK
[    1.036696] [NVT-ts] Resume_PD 189: Resume PD OK
[    1.140322] [NVT-ts] nvt_get_oem_data 706: --
[    1.140359] [NVT-ts] nvt_get_xiaomi_lockdown_info 723: The maker of Touch Panel & CG Lamination: 0x41
[    1.140418] [NVT-ts] nvt_get_xiaomi_lockdown_info 725: Display maker: 0x37
[    1.140477] [NVT-ts] nvt_get_xiaomi_lockdown_info 727: CG ink color: 0x32
[    1.140510] [NVT-ts] nvt_get_xiaomi_lockdown_info 729: HW version: 0x01
[    1.140569] [NVT-ts] nvt_get_xiaomi_lockdown_info 731: Project ID: 0x00F7
[    1.140603] [NVT-ts] nvt_get_xiaomi_lockdown_info 733: CG maker: 0x31
[    1.140661] [NVT-ts] nvt_get_xiaomi_lockdown_info 735: Reservation byte: 0x00
[    1.140720] [NVT-ts] lct_nvt_tp_info_node_init (line 751): LCM information : nt36672a video mode dsi shenchao panel
[    1.140958] [NVT-ts] nvt_flash_proc_init 647: Succeeded!
[    1.141017] [NVT-ts] nvt_flash_proc_init 650: ============================================================
[    1.141049] [NVT-ts] nvt_flash_proc_init 651: Create /proc/NVTflash
[    1.141108] [NVT-ts] nvt_flash_proc_init 652: ============================================================
[    1.141169] [NVT-ts] nvt_extra_proc_init 792: create proc/nvt_fw_version Succeeded!
[    1.141205] [NVT-ts] nvt_extra_proc_init 800: create proc/nvt_baseline Succeeded!
[    1.141265] [NVT-ts] nvt_extra_proc_init 808: create proc/nvt_raw Succeeded!
[    1.141326] [NVT-ts] nvt_extra_proc_init 816: create proc/nvt_diff Succeeded!
[    1.141445] [NVT-ts] nvt_mp_proc_init 2069: create /proc/nvt_selftest Succeeded!
[    1.141511] [NVT-ts] nvt_init_touchmode_data 1303: ENTER
[    1.141572] [NVT-ts] nvt_init_touchmode_data 1353: mode:0, set cur:0, get cur:0, def:0 min:0 max:1
[    1.141631] [NVT-ts] nvt_init_touchmode_data 1353: mode:1, set cur:0, get cur:0, def:1 min:0 max:1
[    1.141666] [NVT-ts] nvt_init_touchmode_data 1353: mode:2, set cur:0, get cur:0, def:0 min:35 max:50
[    1.141727] [NVT-ts] nvt_init_touchmode_data 1353: mode:3, set cur:0, get cur:0, def:112 min:64 max:255
[    1.141786] [NVT-ts] nvt_init_touchmode_data 1353: mode:4, set cur:0, get cur:0, def:0 min:0 max:0
[    1.141846] [NVT-ts] nvt_init_touchmode_data 1353: mode:5, set cur:0, get cur:0, def:0 min:0 max:0
[    1.141905] [NVT-ts] nvt_init_touchmode_data 1353: mode:6, set cur:0, get cur:0, def:0 min:0 max:0
[    1.141939] [NVT-ts] nvt_init_touchmode_data 1353: mode:7, set cur:2, get cur:2, def:2 min:0 max:3
[    1.141999] [NVT-ts] nvt_init_touchmode_data 1353: mode:8, set cur:0, get cur:0, def:0 min:0 max:3
[    1.142058] [NVT-ts] nvt_init_touchmode_data 1353: mode:9, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142117] [NVT-ts] nvt_init_touchmode_data 1353: mode:10, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142177] [NVT-ts] nvt_init_touchmode_data 1353: mode:11, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142211] [NVT-ts] nvt_init_touchmode_data 1353: mode:12, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142270] [NVT-ts] nvt_init_touchmode_data 1353: mode:13, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142329] [NVT-ts] nvt_init_touchmode_data 1353: mode:14, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142388] [NVT-ts] nvt_init_touchmode_data 1353: mode:15, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142446] [NVT-ts] nvt_init_touchmode_data 1353: mode:16, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142479] [NVT-ts] nvt_init_touchmode_data 1353: mode:17, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142538] [NVT-ts] nvt_init_touchmode_data 1353: mode:18, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142596] [NVT-ts] nvt_init_touchmode_data 1353: mode:19, set cur:0, get cur:0, def:0 min:0 max:0
[    1.142690] [NVT-ts] nvt_ts_probe 1838: end
[   14.986719] [NVT-ts] Boot_Update_Firmware (line 1040): g_lcd_id = nt36672a video mode dsi shenchao panel
[   14.986773] [NVT-ts] Boot_Update_Firmware 1044: firmware version is shenchao.
[   14.986800] [NVT-ts] update_firmware_request 55: filename is novatek/shenchao_nt36672a_miui_f7b.bin
[   15.026707] [NVT-ts] Resume_PD 189: Resume PD OK
[   15.193946] [NVT-ts] Check_CheckSum 293: firmware checksum match
[   15.220259] [NVT-ts] Init_BootLoader 346: Init OK
[   15.263363] [NVT-ts] Resume_PD 189: Resume PD OK
[   15.303302] [NVT-ts] nvt_ts_resume 2001: Touch is already resume
[   15.317012] [NVT-ts] nvt_check_flash_end_flag 1015: nvt_end_flag=NVT (4E 56 54)
```

**Comment by sndnvaps** [comment]
my video log 

https://github.com/user-attachments/assets/2006fdd3-a410-4b41-a1fd-dae8593e2cbb

**Comment by Sasmithere** [comment]
@sndnvaps did you try tapping on screen every where ?, i previously updated some key things , try this :

[boot-violet.zip](https://github.com/user-attachments/files/24474824/boot-violet.zip)

**Comment by sndnvaps** [comment]
i had test it. touch screen still not work for me.

https://github.com/user-attachments/assets/3cc4d68d-0c70-4dc0-ac29-705e8618153c

**Comment by Sasmithere** [comment]
@sndnvaps  we both have the same chip , same phone , same everything , it should've worked .... maybe china version has something slightly different ? no , i have a broken firmware in my display and you dont , since my display firmware is broken , 0x01 and 0x62 both accept commands , unlike original which has 0x62 as main , in android it runs in bootloader mode , not in normal mode due to broken firmware , your logs were critical and  i applied a critical fix to it , i'll update in few minutes

https://github.com/user-attachments/assets/cf29e172-9165-4ee6-9643-b0b4308fce16

**Comment by sndnvaps** [comment]
ok, i will test it . when you upload the new build. and gave a feedback.

**Comment by Sasmithere** [comment]
@sndnvaps your logs were a very crucial key !!  , now touch is verify fast and responsive ,i have added a live log to check if its working or not , previously it was a hit and miss for me as well but it worked so i did not think much of it , i have pushed the changed to github at [NovatekTouchDxe](https://github.com/Sasmithere/novatek-touch-dxe )

https://github.com/user-attachments/assets/a0a804e8-c6e9-45a8-a84f-622b33ea0192


[boot-violet.zip](https://github.com/user-attachments/files/24501380/boot-violet.zip)

**Comment by sndnvaps** [comment]
@Sasmithere still not work for me. 
get some err in the loggerd viewer 
```
.... dirty areas in render (in lv_refr.c line #212)
```

https://github.com/user-attachments/assets/17be644d-d6e5-4e51-b577-7060609fdd64

**Comment by Sasmithere** [comment]
@sndnvaps i'll disable EFI_DEVICE_ERROR for this and update the build for testing , i'll be disabling ghost touch filters i have placed as well .

**Comment by Sasmithere** [comment]
@sndnvaps try this ,this 100% should work ,i have disabled many filters ,those filters were for broken firmware ,i have applied actual linux ones instead of my broken one , and this is a test that my build should work in original screens as well , now some ghost touches will be there . give feedback and logs 

[boot-violet.zip](https://github.com/user-attachments/files/24531112/boot-violet.zip)

**Comment by sndnvaps** [comment]
@Sasmithere i had a bad news for you. still not work.

https://github.com/user-attachments/assets/98a36fd4-5a89-4995-9f8d-e1c22c55b07b

**Comment by Sasmithere** [comment]
@sndnvaps you have to tune it yourself , seeing that the chip is identified and its same as mine but no broken firmware , seeing the logs almost  equal to mine , you need to perform some tests yourself . i am currently working on Sdcc part , recompiling from [QcomPkg](https://github.com/Rivko/android-firmware-qti-sdm670.git)

[TouchDxe.zip](https://github.com/user-attachments/files/24543424/TouchDxe.zip)

**Comment by Sasmithere** [comment]
@sndnvaps i have recompiled SdccDxe and its working in PIO mode . i'll attempt DMA mode later , make sure TlmmDxe loads before , or follow the order below 

[order.zip](https://github.com/user-attachments/files/24546635/order.zip)

[SdccDxe.zip](https://github.com/user-attachments/files/24546627/SdccDxe.zip)

<img width="648" height="1152" alt="Image" src="https://github.com/user-attachments/assets/0fb59292-16fa-49fc-bfd0-d8efe58bc3f2" />

**Comment by sndnvaps** [comment]
all right, i need to resync the project from you change. can you push the change to github.com

**Comment by Sasmithere** [comment]
i have pushed the change to my repo, i tried booting windows but it dont go past windows logo

**Comment by Sasmithere** [comment]
can any of the contributors guide me on this ?

<img width="648" height="1152" alt="Image" src="https://github.com/user-attachments/assets/0cdd7d7d-7e69-4757-a48a-d1c999b4f36e" />

**Comment by Sasmithere** [comment]
I need some helping hands to build acpi tables , i have reached windows logon screen , turns out 850 drivers are compatible with sdm675 , well some are anyway, screen stays black because of incomplete acpi tables, on Windows 11 23h2
```
 DevNode 0xffffd407a1784b20 for PDO 0xffffd407a1782bb0
        InstancePath is "ACPI\QCOM246C\0"
        ServiceName is "sdbus"
        State = DeviceNodeStarted (0x30a)
        Previous State = DeviceNodeEnumerateCompletion (0x30f)
        DevNode 0xffffd407a17aac20 for PDO 0xffffd407a1789060
          InstancePath is "SD\VID_90&OID_004a&PID_hC8aP>&REV_0.3\3&86c7db4&0&0"
          ServiceName is "sdstor"
          State = DeviceNodeStarted (0x30a)
          Previous State = DeviceNodeEnumerateCompletion (0x30f)
          DevNode 0xffffd407a19e8ae0 for PDO 0xffffd407a19e4b40
            InstancePath is "SD\DISK&Hynix&hC8aP>&0.3\4&27e8ebd3&0&48a98858&0"
            ServiceName is "disk"
            TargetDeviceNotify List - f 0xffffc2081507d490  b 0xffffc20815343310
            State = DeviceNodeStarted (0x30a)
            Previous State = DeviceNodeEnumerateCompletion (0x30f)
      DevNode 0xffffd407a1785010 for PDO 0xffffd407a1782de0
        InstancePath is "ACPI\QCOM246C\1"
        ServiceName is "sdbus"
        State = DeviceNodeStarted (0x30a)
        Previous State = DeviceNodeEnumerateCompletion (0x30f)
      DevNode 0xffffd407a17853c0 for PDO 0xffffd407a08eb9d0
        InstancePath is "ACPI\QCOM0216\1"
        ServiceName is "qcspmi"
        TargetDeviceNotify List - f 0xffffc20814ea7690  b 0xffffc20814ea7690
        State = DeviceNodeStarted (0x30a)
        Previous State = DeviceNodeEnumerateCompletion (0x30f)
      DevNode 0xffffd407a1785770 for PDO 0xffffd407a08ebc00
        InstancePath is "ACPI\QCOM0266\0"
        ServiceName is "qcpmic"
        State = DeviceNodeStarted (0x30a)
        Previous State = DeviceNodeEnumerateCompletion (0x30f)
      DevNode 0xffffd407a1785b20 for PDO 0xffffd407a1783060
        InstancePath is "ACPI\QCOM0224\0"
        State = DeviceNodeInitialized (0x304)
        Previous State = DeviceNodeUninitialized (0x301)
        Problem = CM_PROB_FAILED_INSTALL
        Problem Status = 0xc0000490
      DevNode 0xffffd407a17863c0 for PDO 0xffffd407a17834c0
        InstancePath is "ACPI\QCOM0214\0"
        ServiceName is "qcscm"
        TargetDeviceNotify List - f 0xffffc2081507e910  b 0xffffc20815342310
        State = DeviceNodeStarted (0x30a)
        Previous State = DeviceNodeEnumerateCompletion (0x30f)
      DevNode 0xffffd407a1786770 for PDO 0xffffd407a17836f0
        InstancePath is "ACPI\QCOM027E\0"
        State = DeviceNodeInitialized (0x304)
        Previous State = DeviceNodeUninitialized (0x301)
        Problem = CM_PROB_FAILED_INSTALL
        Problem Status = 0xc0000490
      DevNode 0xffffd407a1ee69d0 for PDO 0xffffd407a1783290
        InstancePath is "ACPI\QCOM0217\0"
        ServiceName is "qcgpio"
        State = DeviceNodeRemoved (0x314)
        Previous State = DeviceNodeStartCompletion (0x308)
        Problem = CM_PROB_FAILED_START
        Problem Status = 0xc0000001
        Failure Status 0000000000
        
        
  DevNode 0xffffd407a0c06840 for PDO 0xffffd407a0c06650
    InstancePath is "ROOT\BasicRender\0000"
    ServiceName is "BasicRender"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeEnumerateCompletion (0x30f)
  DevNode 0xffffd407a0c07010 for PDO 0xffffd407a0c06c40
    InstancePath is "ROOT\NdisVirtualBus\0000"
    ServiceName is "NdisVirtualBus"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeEnumerateCompletion (0x30f)
  DevNode 0xffffd407a0c07600 for PDO 0xffffd407a0c07410
    InstancePath is "ROOT\mssmbios\0000"
    ServiceName is "mssmbios"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeEnumerateCompletion (0x30f)
  DevNode 0xffffd407a0c07bf0 for PDO 0xffffd407a0c07a00
    InstancePath is "ROOT\SYSTEM\0000"
    ServiceName is "swenum"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeEnumerateCompletion (0x30f)
  DevNode 0xffffd407a0c08250 for PDO 0xffffd407a0c08060
    InstancePath is "ROOT\RDPBUS\0000"
    ServiceName is "rdpbus"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeEnumerateCompletion (0x30f)
  DevNode 0xffffd407a17a5b20 for PDO 0xffffd407a17a5930
    InstancePath is "SWD\COMPUTER\MFG_Xiaomi&FAM_Snapdragon_845_Device&PROD_Redmi_Note_7_Pro&SKU_SKU_Not_Set"
    State = DeviceNodeStarted (0x30a)
    Previous State = DeviceNodeStartPostWork (0x309)

kd> !process 0 0
**** NT ACTIVE PROCESS DUMP ****
PROCESS ffffd407a0894080
    SessionId: none  Cid: 0004    Peb: 00000000  ParentCid: 0000
    DirBase: 85daa000  ObjectTable: ffffc20814a04b00  HandleCount: 920.
    Image: System

PROCESS ffffd407a0ad3080
    SessionId: none  Cid: 008c    Peb: 00000000  ParentCid: 0004
    DirBase: 17db08000  ObjectTable: ffffc20814a0f5c0  HandleCount:   0.
    Image: Registry

PROCESS ffffd407a405c080
    SessionId: none  Cid: 0208    Peb: 26a6eca000  ParentCid: 0004
    DirBase: 105d1b000  ObjectTable: ffffc208151e16c0  HandleCount:  57.
    Image: smss.exe

PROCESS ffffd407a4504080
    SessionId: 0  Cid: 02c0    Peb: 59b0b48000  ParentCid: 02b8
    DirBase: 10affd000  ObjectTable: ffffc20818185640  HandleCount: 199.
    Image: csrss.exe

PROCESS ffffd407a46e1080
    SessionId: 0  Cid: 0308    Peb: 6010a4c000  ParentCid: 02b8
    DirBase: 10a177000  ObjectTable: ffffc20818178940  HandleCount: 187.
    Image: wininit.exe

PROCESS ffffd407a46ed080
    SessionId: 1  Cid: 0310    Peb: 7a7720a000  ParentCid: 0300
    DirBase: 109b4c000  ObjectTable: ffffc20817010a80  HandleCount: 157.
    Image: csrss.exe

PROCESS ffffd407a473d080
    SessionId: 1  Cid: 0350    Peb: cb2cb64000  ParentCid: 0300
    DirBase: 1117c6000  ObjectTable: ffffc20817002a80  HandleCount: 216.
    Image: winlogon.exe

PROCESS ffffd407a45d0100
    SessionId: 0  Cid: 039c    Peb: 66ed249000  ParentCid: 0308
    DirBase: 10cd8e000  ObjectTable: ffffc20817110040  HandleCount: 252.
    Image: services.exe

PROCESS ffffd407a4502100
    SessionId: 0  Cid: 03b4    Peb: df09eb7000  ParentCid: 0308
    DirBase: 1106fc000  ObjectTable: ffffc208171f79c0  HandleCount: 654.
    Image: lsass.exe

PROCESS ffffd407a4970100
    SessionId: 0  Cid: 0294    Peb: 91377c3000  ParentCid: 039c
    DirBase: 10fa0c000  ObjectTable: ffffc20817508680  HandleCount: 307.
    Image: svchost.exe

PROCESS ffffd407a4975080
    SessionId: 1  Cid: 02bc    Peb: 99595a3000  ParentCid: 0350
    DirBase: 114079000  ObjectTable: ffffc20817511200  HandleCount:  41.
    Image: fontdrvhost.exe

PROCESS ffffd407a48f1080
    SessionId: 0  Cid: 028c    Peb: cd7be9000  ParentCid: 0308
    DirBase: 113b9b000  ObjectTable: ffffc2081750cac0  HandleCount:  41.
    Image: fontdrvhost.exe

PROCESS ffffd407a4a20080
    SessionId: 0  Cid: 042c    Peb: b82a9c1000  ParentCid: 039c
    DirBase: 110bd5000  ObjectTable: ffffc208176b86c0  HandleCount: 239.
    Image: svchost.exe

PROCESS ffffd407a4a47080
    SessionId: 0  Cid: 0454    Peb: f6351f000  ParentCid: 039c
    DirBase: 110d41000  ObjectTable: ffffc2081771d6c0  HandleCount: 237.
    Image: svchost.exe

PROCESS ffffd407a4b43080
    SessionId: 0  Cid: 0484    Peb: ae4e991000  ParentCid: 039c
    DirBase: 10eff0000  ObjectTable: ffffc208178659c0  HandleCount: 230.
    Image: sppsvc.exe

PROCESS ffffd407a4b82080
    SessionId: 0  Cid: 04ac    Peb: fb25a32000  ParentCid: 039c
    DirBase: 1168ff000  ObjectTable: ffffc208178a7ac0  HandleCount:  90.
    Image: svchost.exe

PROCESS ffffd407a4b83080
    SessionId: 0  Cid: 04d0    Peb: f848bac000  ParentCid: 039c
    DirBase: 116b18000  ObjectTable: ffffc208178aa040  HandleCount: 129.
    Image: svchost.exe

PROCESS ffffd407a4b80080
    SessionId: 0  Cid: 04f8    Peb: cf3db8a000  ParentCid: 039c
    DirBase: 1130d2000  ObjectTable: ffffc2081786d040  HandleCount: 128.
    Image: svchost.exe

PROCESS ffffd407a4bb8100
    SessionId: 1  Cid: 0520    Peb: 740f9e1000  ParentCid: 0350
    DirBase: 114d89000  ObjectTable: ffffc2081791b040  HandleCount: 736.
    Image: dwm.exe

PROCESS ffffd407a4c13100
    SessionId: 1  Cid: 0528    Peb: 7fefa52000  ParentCid: 0350
    DirBase: 114cfd000  ObjectTable: ffffc20817919a80  HandleCount: 402.
    Image: LogonUI.exe

PROCESS ffffd407a4c87080
    SessionId: 0  Cid: 05bc    Peb: 72da02c000  ParentCid: 039c
    DirBase: 11501c000  ObjectTable: ffffc20817a47880  HandleCount: 127.
    Image: svchost.exe

PROCESS ffffd407a0877080
    SessionId: 0  Cid: 0634    Peb: 1c7aa83000  ParentCid: 039c
    DirBase: 11b989000  ObjectTable: ffffc20817bc6ac0  HandleCount: 155.
    Image: svchost.exe
```

**Comment by Sasmithere** [comment]
my project of porting is done , but without much qc drivers 

<img width="438" height="933" alt="Image" src="https://github.com/user-attachments/assets/05e4d80e-5ff9-4106-b0f3-cea3365f56ba" />

<img width="648" height="1152" alt="Image" src="https://github.com/user-attachments/assets/1f4e859c-e6ae-4b29-9042-28f577245ba7" />

**Comment by Sasmithere** [comment]
i made my own kmdf touch driver using wdk and visual studio 2022, using hardware i2c so i think it should work , but since my phones display is a cheap replacement ips tft , i dont know the behaviour other phones of same type would have @sndnvaps

**Comment by sndnvaps** [comment]
@Sasmithere can you upload the violet-boot.img,i will test it as soon as possible.

**Comment by Sasmithere** [comment]
@sndnvaps [boot-violet.zip](https://github.com/user-attachments/files/30385668/boot-violet.zip)
it isnt my final build or you can say its a incomplete build but just enough to boot windows for now, i'll finish some time later
